version: 2
project_name: mosquitto-exporter
builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers_v2:
- images: ["jryberg/mosquitto-exporter"]
  tags: ["{{ .Tag }}"]
  platforms:
  - linux/amd64
  - linux/arm64
changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Build"
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test"
      - "^typo"
      - "^ci"
    include:
      - "^build"
      - "^feat"
      - "^fix"
      - "^perf"
      - "^refactor"
      - "^style"