FROM golang:1.27-bookworm@sha256:6ed48491acfb40533f6970d9d8ce3cbfc6f2cc7d81413c2f01c871c927d98634 AS build

WORKDIR /go/src/app

## Download modules and store, this optimizes use of Docker image cache
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN make build

FROM debian:trixie-slim@sha256:d7e12182ce18b85b93007c1dedf31f2d29e01ccf3182cc4017c709b6259bc132
LABEL source_repository="https://github.com/jryberg/mosquitto-exporter"

COPY --from=build /go/src/app/bin/mosquitto_exporter /mosquitto_exporter
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests ca-certificates && \
    rm -rf /var/lib/apt/lists/*
EXPOSE 9234

ENTRYPOINT [ "/mosquitto_exporter" ]
